# Copyright (c) 2026 PotterWhite
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import logging
import yaml
import os
import glob

from .input_signature import InputSignature

# Global logger instance
logger = logging.getLogger("ArcFoundry")


def load_config_file(path):
    with open(path, "r") as f:
        return yaml.safe_load(f)


def cleanup_garbage(target_dir=".", patterns=None):
    """
    Cleans up temporary/garbage files matching specific patterns.

    Args:
        target_dir (str): Directory to search in. Defaults to current CWD.
        patterns (list): List of glob patterns. Defaults to RKNN junk files.
    """
    if patterns is None:
        # Default junk generated by RKNN C++ backend
        patterns = ["check*.onnx", "encoder.processed.*", "*.rknn_util_Config"]

    if 'logger' in globals():
        logger.info(f"\n🧹 Cleaning up junk files in {target_dir}...")

    for pattern in patterns:
        search_path = os.path.join(target_dir, pattern)

        found_files = glob.glob(search_path)

        for f in found_files:
            try:
                if os.path.exists(f):
                    os.remove(f)
                    if 'logger' in globals():
                        # Use global logger if available
                        # global means who invoked this function has already setup logging
                        logger.info(f"🧹 Cleaned up junk file: {f}")
            except OSError as e:
                if 'logger' in globals():
                    logger.error(f"Failed to delete file {f}: {str(e)}")

    if 'logger' in globals():
        logger.info(f"\n🧹 Cleanup complete.\n")


def ensure_dir(path):
    if not os.path.exists(path):
        os.makedirs(path)


def get_sdk_version():
    """
    Simple parser to get version from pyproject.toml (SSOT).
    """
    try:
        # Locate project root (assuming core/utils.py is in core/)
        root_dir = os.path.dirname(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        toml_path = os.path.join(root_dir, "pyproject.toml")

        if os.path.exists(toml_path):
            with open(toml_path, 'r') as f:
                for line in f:
                    if line.strip().startswith("version"):
                        return line.split('=')[1].strip().strip('"').strip("'")
    except Exception:
        pass
    return "unknown"


def get_input_signature_from_yaml(cfg, model_name=None):
    """
    Extract input signature from YAML config.
    If model_name is None, use the first model.
    """

    models = cfg.get("models", [])

    if not models:
        raise ValueError("No models found in YAML.")

    # If model_name specified, filter it
    if model_name:
        models = [m for m in models if m.get("name") == model_name]
        if not models:
            raise ValueError(f"Model {model_name} not found in YAML.")

    model = models[0]

    input_shapes = model.get("input_shapes", [])
    if not input_shapes:
        raise ValueError(f"Model {model.get('name')} has no input_shapes.")

    shape = input_shapes[0]

    return InputSignature(shape)
