# Copyright (c) 2026 PotterWhite
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import logging
import sys
import os
import glob
import select


# 1. Define the Custom Formatter
class SmartNewlineFormatter(logging.Formatter):
    """
    A custom formatter that detects leading newlines in the log message
    and moves them to the very beginning of the final output string,
    before the log prefix (timestamp, level, etc.).
    """

    def format(self, record):
        # Ensure message is a string
        original_msg = str(record.msg)

        # Check for leading newlines
        if original_msg.startswith('\n'):
            # Calculate the number of leading newlines
            stripped_msg = original_msg.lstrip('\n')
            newline_count = len(original_msg) - len(stripped_msg)
            prefix_newlines = '\n' * newline_count

            # --- The Trick ---
            # 1. Temporarily strip newlines from the record message
            record.msg = stripped_msg

            # 2. Let the parent class format the standard line (Prefix + Message)
            formatted_line = super().format(record)

            # 3. Restore the original message (good practice for other handlers)
            record.msg = original_msg

            # 4. Prepend the newlines to the very front
            return prefix_newlines + formatted_line

        # Default behavior for messages without leading newlines
        return super().format(record)


def get_btf_from_yaml(cfg, model_name="encoder"):
    models = cfg.get("models", [])

    for model in models:
        if model.get("name") == model_name:
            input_shapes = model.get("input_shapes", [])
            if not input_shapes:
                raise ValueError(f"{model_name} has no input_shapes")

            shape = input_shapes[0]

            if len(shape) != 3:
                raise ValueError(f"Expect shape [B, T, F], got {shape}")

            B, T, F = shape
            return B, T, F

    raise ValueError(f"Model {model_name} not found in yaml")


# Global logger instance
logger = logging.getLogger("ArcFoundry")


def ensure_dir(path):
    if not os.path.exists(path):
        os.makedirs(path)


def timed_input(prompt, timeout=30, default='y'):
    """
    Waits for user input with a countdown. Returns default if timeout.
    Works on Linux/Unix systems.
    """
    sys.stdout.write(f"{prompt} (Timeout: {timeout}s, Default: {default.upper()}): ")
    sys.stdout.flush()

    # Monitor sys.stdin for input
    ready, _, _ = select.select([sys.stdin], [], [], timeout)

    if ready:
        user_input = sys.stdin.readline().strip().lower()
        return user_input if user_input else default
    else:
        sys.stdout.write(f"\n[TIMEOUT] No input received. Auto-selecting default: {default.upper()}\n")
        return default


def cleanup_garbage(target_dir=".", patterns=None):
    """
    Cleans up temporary/garbage files matching specific patterns.

    Args:
        target_dir (str): Directory to search in. Defaults to current CWD.
        patterns (list): List of glob patterns. Defaults to RKNN junk files.
    """
    if patterns is None:
        # Default junk generated by RKNN C++ backend
        patterns = ["check*.onnx", "encoder.processed.*", "*.rknn_util_Config"]

    if 'logger' in globals():
        logger.info(f"\n🧹 Cleaning up junk files in {target_dir}...")

    for pattern in patterns:
        search_path = os.path.join(target_dir, pattern)

        found_files = glob.glob(search_path)

        for f in found_files:
            try:
                if os.path.exists(f):
                    os.remove(f)
                    if 'logger' in globals():
                        # Use global logger if available
                        # global means who invoked this function has already setup logging
                        logger.info(f"🧹 Cleaned up junk file: {f}")
            except OSError as e:
                if 'logger' in globals():
                    logger.error(f"Failed to delete file {f}: {str(e)}")

    if 'logger' in globals():
        logger.info(f"\n🧹 Cleanup complete.\n")


def get_sdk_version():
    """
    Simple parser to get version from pyproject.toml (SSOT).
    """
    try:
        # Locate project root (assuming core/utils.py is in core/)
        root_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        toml_path = os.path.join(root_dir, "pyproject.toml")

        if os.path.exists(toml_path):
            with open(toml_path, 'r') as f:
                for line in f:
                    if line.strip().startswith("version"):
                        return line.split('=')[1].strip().strip('"').strip("'")
    except Exception:
        pass
    return "unknown"


def setup_logging(verbose=False):
    """
    Configure logging with version info and verbosity control.
    """
    ver = get_sdk_version()

    # Determine Log Level
    log_level = logging.DEBUG if verbose else logging.INFO

    # Create Formatter
    # formatter = logging.Formatter(
    #     fmt=f"[ArcFoundry v{ver}] %(asctime)s [%(levelname)s] %(message)s",
    #     datefmt="%H:%M:%S"
    # )
    formatter = SmartNewlineFormatter(fmt=f"[ArcFoundry v{ver}] %(asctime)s [%(levelname)s] %(message)s",
                                      datefmt="%H:%M:%S")

    # Setup Root Logger
    root_logger = logging.getLogger()
    root_logger.setLevel(log_level)

    # Avoid duplicate handlers if re-initialized
    if not root_logger.handlers:
        console_handler = logging.StreamHandler(sys.stdout)
        console_handler.setFormatter(formatter)
        root_logger.addHandler(console_handler)

    # Suppress noisy libraries
    logging.getLogger("urllib3").setLevel(logging.WARNING)
    logging.getLogger("onnxruntime").setLevel(logging.WARNING)

    return logging.getLogger("ArcFoundry")


# Initialize a default logger instance for module-level usage
logger = setup_logging(verbose=False)
